database: sqlite3
dsn: file::memory:?mode=memory&cache=shared&loc=Asia/Shanghai
#dsn: gorm.db?mode=memory&cache=shared&loc=Asia/Shanghai
port: 8080
logger:
  level: info
  format: "2006-01-02 15:04:05"